spring.application.name=KebabeLoginWebpage
server.port=8080
review.service.url=http://localhost:8082

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:logindb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

